name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
```

Please note that this is a basic template and may need to be customized based on your specific project requirements and dependencies. Make sure to replace the placeholder values with the appropriate actions, commands, and configurations for your project.

For the unit tests, you should create comprehensive tests that cover all relevant scenarios and edge cases. Here is an example of a unit test for the build step:

```javascript
test('Build step should run successfully', () => {
  // Mock any necessary dependencies or setup

  // Run the build step

  // Assert the expected outcome or result
});
